# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  # config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "lamp"
    v.memory = 512
    v.cpus = 1
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.hostname = "lamp"
  config.vm.network :private_network, ip: "192.168.33.27"

  # config.vm.synced_folder ".", "/shared"
#  config.vm.synced_folder "/Users/Egor/Downloads/pyth/booker", "/z/booker"
  config.vm.synced_folder "/Users/Egor/work", "/z/work"
end
