#!/usr/bin/env ruby

require 'optparse'

# Set working dir
Dir.chdir(__dir__)

# Define available options here
# ARGV << '-h' if ARGV.empty? || !(ARGV.first.start_with? '-')
ARGV << '-h' if ARGV.empty?

def run_action
  case ARGV.shift
  when 'list'
    options = {}
    parser = OptionParser.new do |op|
      op.on("-e", "--ext [EXTENSION]", "List available docker-composes") { |o| options[:extension] = o }
      op.on_tail("-h", "--help", "Show this message") { puts op; exit }
    end.parse!
    Act.list options
  when 'run'
    options = {}
    parser = OptionParser.new do |op|
      op.on("-d", "--detached", "List available docker-composes") { |o| options[:detached] = o }
      op.on("-e", "--ext [EXTENSION]", "List available docker-composes") { |o| options[:extension] = o }
      op.on_tail("-h", "--help", "Show this message") { puts op; exit }
    end.parse!
    Act.list options
  when nil, '-h', '--help'
    puts "Usage: devopser [command] [options [args]]"
  when '--version', nil
    puts '1.0.0'
  end
end

# Define all actions here
class Act
  def self.list(opts)
    puts 'Available docker-compose items:'
    Dir.glob('composes/*').each do |f| 
      puts File.basename f if File.directory? f
    end
  end
end

# Just run
run_action