version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redis_net

  ui:
    depends_on:
      - redis
    image: ghcr.io/joeferner/redis-commander
    container_name: redis_comndr
    ports:
      - 8081:8081
    links:
      - redis:redis
    environment:
      - REDIS_HOST=eventbus
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
