# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.ssh.insert_key = false

  vm_name = "bazel"

  config.vm.provider :virtualbox do |v|
    v.name = vm_name
    v.memory = 1024
    v.cpus = 1
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell", path: "provision.sh", privileged: true
  config.vm.network :private_network, ip: "192.168.70.70"

  config.vm.hostname = vm_name
  config.vm.synced_folder "~/work", "/shared/work"
  # config.vm.synced_folder "~/bin/bazel-linux-vagrant-out", "/Users/YOURNAME/bin/bazel-linux-vagrant-out"
end
