version: '2'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus_cntr
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - ./alertmanager.yml:/etc/prometheus/alertmanager.yml
    # network_mode: "host"
    # networks:
    #   - prom_graph_net

  grafana:
    image: grafana/grafana
    container_name: grafana_cntr
    ports:
      - 3000:3000
    # use admin/admin
    # environment:
    #   - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./extra/grafana_db:/var/lib/grafana grafana/grafana
    # network_mode: "host"
    # networks:
    #   - prom_graph_net


# networks:
#   prom_graph_net:
#     driver: host