global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'sweet-monitor'

rule_files:
    - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:7777'] # it should be forwarded from minikube to host
        labels:
          group: 'honey'

  - job_name: 'sts'
    scrape_interval: 1s
    metrics_path: '/health/prometheus'
    static_configs:
      - targets: ['docker.for.mac.localhost:7777'] # it should be forwarded from minikube to host
        labels:
          group: 'honey'

  - job_name: 'sts-direct'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:4444'] # it should be forwarded from minikube to host
        labels:
          group: 'honey'
