global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'sweet-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'local'

  - job_name: 'sweet'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.2:8088']
        labels:
          group: 'honey'
